### ISSUE TITLE
Please remove the node-red keyword

### ISSUE THREAD

**Issue by TotallyInformation** [mathiasrw/node-red-contrib-alasql#1]
Hi there, could I please ask that you remove the node-red keyword from the package.json until this actually works? That will remove it from the flows listing and prevent people from having problems by installing it before it is ready.

Thanks.

**Comment by knolleary** [comment]
I've had a quick look - the issue is there's no edit template for the node in the .html file.

Simply adding:

    <script type="text/x-red" data-template-name="alasql"></script>

is enough to stop it breaking the editor. Presumably it must have some properties that need configuring so will need some sort of edit template?

This has been a useful test case to highlight an area where we need better error handling and reporting to the user; thanks!

**Comment by mathiasrw** [comment]
Thank you for taking the time to come with feedback. 

I will edit it right away

**Comment by mathiasrw** [comment]
https://www.npmjs.com/browse/keyword/node-red now does not show this package

**Comment by TotallyInformation** [comment]
Just to say that I look forward to a working version. I'm quite interested in alasql, though it still seems to have some way to go in its development, it could be a very useful tool.

**Comment by mathiasrw** [comment]
Hi @TotallyInformation @knolleary 

Just to let you know the code was updated and should be working now. 

I readded the node-red keyword. Do you know if we need to do anything else to get the library into the list at http://flows.nodered.org/ ?
